(function() {var implementors = {};
implementors["openexr"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"openexr/frame_buffer/struct.FrameBuffer.html\" title=\"struct openexr::frame_buffer::FrameBuffer\">FrameBuffer</a>&lt;'a&gt;",synthetic:false,types:["openexr::frame_buffer::FrameBuffer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"openexr/header/struct.Header.html\" title=\"struct openexr::header::Header\">Header</a>",synthetic:false,types:["openexr::header::Header"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"openexr/header/struct.ChannelIter.html\" title=\"struct openexr::header::ChannelIter\">ChannelIter</a>&lt;'a&gt;",synthetic:false,types:["openexr::header::ChannelIter"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"openexr/input/struct.InputFile.html\" title=\"struct openexr::input::InputFile\">InputFile</a>&lt;'a&gt;",synthetic:false,types:["openexr::input::InputFile"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/drop/trait.Drop.html\" title=\"trait core::ops::drop::Drop\">Drop</a> for <a class=\"struct\" href=\"openexr/struct.ScanlineOutputFile.html\" title=\"struct openexr::ScanlineOutputFile\">ScanlineOutputFile</a>&lt;'a&gt;",synthetic:false,types:["openexr::output::scanline_output_file::ScanlineOutputFile"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
